version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USE_POSTGRES=false
      - JWT_SECRET=your_super_secret_jwt_key_here_change_in_production
      - BASE_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
