
version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USE_POSTGRES=false
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nightscout_api
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - JWT_SECRET=your_super_secret_jwt_key_here_change_in_production
      - BASE_URL=http://localhost:3000
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=nightscout_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
